### ISSUE TITLE
The "-download-paid-fanclubs" (-p) option only retrieve the paid plans of the first page of the paid plan list

### ISSUE THREAD

**Issue by thibo1138** [bitbybyte/fantiadl#100]
I have the issue where I have a paid plan list on 2 pages in fantia
but fantidl only retrieve the fanclubs of the first page when using -p option
and i have to download the other plans one by one after 

Could it be possible for the -p option to access the plans on all pages of the paid plan list?

the -f might be affected too with the same issue but i didn't test it

**Comment by bitbybyte** [comment]
Only paid fanclubs would be affected. We'll need to know what the second paginated URL looks like so we can loop over the HTML. As far as I know the following API doesn't have filtering on paid clubs.

**Comment by thibo1138** [comment]
the address become like this on page 2 : 

https://fantia.jp/mypage/users/plans?page=2&type=not_free

**Comment by bitbybyte** [comment]
Please check on the https://github.com/bitbybyte/fantiadl/tree/fetch-all-not-free-pages branch to see if that works for you.

**Comment by bitbybyte** [comment]
@thibo1138 Have you tried?

**Comment by thibo1138** [comment]
yes, I tried just now and it worked perfectly

thank you

**Comment by bitbybyte** [comment]
Thanks for checking! Will merge in soon.
