### ISSUE TITLE
It doesnt seems to work for me

### ISSUE THREAD

**Issue by BlackCat75** [bitbybyte/fantiadl#101]
Hello, im sorry but i've no experience with .py file and somehow i cannot make the thing work, whenever i opens the files and type -c (paste session id here) and press enter the software simply closes and i get nothing out if, sorry if im failing a very simple task but could someone help me on this one?

thank u in advance!

**Comment by bitbybyte** [comment]
There's an executable under Releases. You're encouraged to check the README and use Discussions rather than opening an issue.
