### ISSUE TITLE
X-Requested-With header required for post API

### ISSUE THREAD

**Issue by key050365** [bitbybyte/fantiadl#118]
I use powershell to enter the code：
D:\Program\fantiadl\fantiadl_v1.8.4.exe --cookie [my session_id] --use-server-filenames --mark-incomplete-posts --output-directory H:\Downloads\Fantia https://fantia.jp/fanclubs/[the author id]

it show me:
Downloading fanclub [the author id]...
Collecting fanclub posts...
Collected 296 posts.
Downloading post [the post id]...
Traceback (most recent call last):
  File "fantiadl.py", line 120, in <module>
  File "models.py", line 229, in download_fanclub
  File "models.py", line 475, in download_post
  File "requests\models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 422 Client Error: unknown for url: https://fantia.jp/api/v1/posts/[the post id]
[12596] Failed to execute script 'fantiadl' due to unhandled exception!

![7OE$R`}_66JD7Z) SS1RWR4](https://github.com/bitbybyte/fantiadl/assets/96135499/5029050e-5b62-4bed-93b0-c22403ea34c0)

**Comment by angramainyuu** [comment]
I can confirm it just stopped working today.

**Comment by bitbybyte** [comment]
Setting `"X-Requested-With": "XMLHttpRequest"` on the request should fix this.
