### ISSUE TITLE
Preserve data on post title change

### ISSUE THREAD

**Issue by Suika** [bitbybyte/fantiadl#17]
From time to time, creators will change the title of their post.
Due to the way the paths are constructed in fantiadl, that causes file duplication.

The post ID is the only thing that doesn't change.

Solution:
1. if post ID directory already exists, check files and download new files if size differs
2. rename old metadata .json and download new metadata as usual
3. rename directory to new title

**Comment by IIJlOXOCIIAJl** [comment]
How to enable this option? Initially, folders with the names of numbers are created.
