### ISSUE TITLE
"No valid input provided"

### ISSUE THREAD

**Issue by IceyGlaze** [bitbybyte/fantiadl#18]
I already has Requests and Python 3.7 installed but it still gives me "Error: No valid input provided"

**Comment by bitbybyte** [comment]
You could start by posting a traceback or the command you used? Just use [the binary](https://github.com/bitbybyte/fantiadl/releases/) if you're having problems.

**Comment by deed459** [comment]
The program keeps shutting down instantly after I click on it

**Comment by febirizky** [comment]
New version need py 3.9.x?
