### ISSUE TITLE
unable to open the executable programme

### ISSUE THREAD

**Issue by Ksdpm** [bitbybyte/fantiadl#21]
Hi,

For some reason whenever I open 'fantiadl_v1.3.3.exe', it always return the message 'Error: No valid input provided'. While I am able to execute the python source code directly i.e. using visual studio or SPYDER , I just cannot open 'fantiadl_v1.3.3.exe'. What is the way to resolve it?

Cheers

**Comment by bitbybyte** [comment]
`usage: fantiadl.py [options] url`

The same applies for the executable.
