### ISSUE TITLE
Status code 304 from API "fantia.jp/api/v1/me"

### ISSUE THREAD

**Issue by zyzmrx** [bitbybyte/fantiadl#26]
Hi bitbybyte,

On June 14th, 2020, a download was interrupted when I was using the downloader. The program keep return "Error: Invalid session" since that time. 

I tried to trouble shooting it. I reviewed the source code and check the webpage "https://fantia.jp/api/v1/me" by developer tools on firedox 77.0.1 & Chrome 83.0.4103.106. The page status code is 304 instead of 200.

Did you have the same problem? I am not sure if fantia made some change on their server or there is some cache issue on my side.

Thank you and have a nice day,

**Comment by bitbybyte** [comment]
304 is a valid response too, so I think if I change this check to be less specific you shouldn't have any problems. I'll patch this soon.

**Comment by zyzmrx** [comment]
Thank you for the update.
