### ISSUE TITLE
Login process now requires reCAPTCHA

### ISSUE THREAD

**Issue by tenyuhuang** [bitbybyte/fantiadl#28]
As the title says, fantiadl will return an `Error: Invalid session` after a password change; and it's not a wrong password either - on wrong password, it will threw "Error: Failed to login. Please verify your username and password", but with the new one, it will just return "Invalid session" instead.

Tried again on a different network and OS, didn't work.

Could you look into the issue? Thanks in advance!

**Comment by bitbybyte** [comment]
Are you using the binary? This should have been addressed in #26. I uploaded a [new release](https://github.com/bitbybyte/fantiadl/releases/tag/v1.4.3) so please let me know if the issue persists.

**Comment by EivV** [comment]
I am using the source version (have just tried the new 1.4.3) and the session is still invalid. The response code 401.

**Comment by bitbybyte** [comment]
I guess the login process has changed as https://id.fantia.jp/auth/login now fails and login is done at https://fantia.jp/sessions/signin. That requires reCAPTCHA so the only option now may be having the user provide their session cookie.

**Comment by EivV** [comment]
I wouldn't mind the change. If there is a place in-source where I could set the hard-coded value, that would be enough for me. If there was a CLI option, then even better.

**Comment by bitbybyte** [comment]
Ideally I think oy should have -c/--cookie to provide it directly and also a way to read from a `cookies.txt`, so I'll try to include both.

**Comment by tenyuhuang** [comment]
Yeah the binary has the same issue, I'll try again with `_session_id` when you implement it.

**Comment by bitbybyte** [comment]
@EivV Please test from this branch: https://github.com/bitbybyte/fantiadl/tree/use-session-cookie

**Comment by EivV** [comment]
Yes, it is working now.
