### ISSUE TITLE
Can this project can set download dirctory?

### ISSUE THREAD

**Issue by railannad** [bitbybyte/fantiadl#31]
This script is very convenient and it helps me a lot , thank you. 
But I can not find how to set download dirctory. For example , you can see [this](https://github.com/Nandaka/PixivUtil2#filename-format-syntax) script . 

If edit "config.ini" and type "%artist%/%urlFilename%" , Then all files will be downloaded in a same dirctory , such as following pictures
![image](https://user-images.githubusercontent.com/36919867/89846316-74987980-dbb3-11ea-80c1-b0c66cff484e.png)

And if edit "config.ini" as "%artist%/%member_id%/%urlFilename%/" , then the script will create dirctory for every post , like this 
![image](https://user-images.githubusercontent.com/36919867/89846398-b75a5180-dbb3-11ea-9419-ac81841f106d.png)

Fantiadl will create dirctory for every post like example 2  defaultly, then please tell me how to let "fantiadl" downloads files like example 1

**Comment by bitbybyte** [comment]
Unfortunately I don't have any plans to add custom filename templating right now as the script is built around the directory structure. Other than maybe your example, I don't see much value in adding full customization.

You can achieve what you want using xcopy in Command Prompt. This'll only work if you download using the --use-server-filenames flag: `for /r %i in (*) do xcopy /Y "%i" C:\path\to\output\directory`
