### ISSUE TITLE
it keeps saying no valid input provided

### ISSUE THREAD

**Issue by tranvinhkhanh39** [bitbybyte/fantiadl#32]
it keeps saying no valid input provided

**Comment by bitbybyte** [comment]
Either post the input you used or read the README.

**Comment by SirDerpTheDerp** [comment]
Unsure if I am even supposed to post my questions here (and I apologize if I am not), I have a question regarding the .exe file provided in the download. After completing the download, I had tried to open the .exe however it just quickly opens and closes again. I'm unsure if this is on my end or I'm just dumb, new to python and don't know what is happening. Again apologies if I am not supposed to post here.

**Comment by bitbybyte** [comment]
It's a command line program, not a GUI. You don't double click it to run it.
