### ISSUE TITLE
can't login with _session_id cookie or cookies.txt

### ISSUE THREAD

**Issue by hunterinawheelchair** [bitbybyte/fantiadl#37]
Hello, when i'm trying to connect to my fantia account with   _session_id cookie  cookies.txt i'am getting a error that tell me that my session cookie is invalide. i've tried to wait and delete it and connecting with the new one but i'm still getting this error.  am I doing something wrong?

![dfsf](https://user-images.githubusercontent.com/74125516/98456706-3fcf9a80-2181-11eb-82e0-e08b6ef7b6fc.png)

**Comment by bitbybyte** [comment]
Remove the SESSION_COOKIE from the argument, it's either the bare cookie value or the filename, e.g. `-s cookies.txt`.

**Comment by hunterinawheelchair** [comment]
i'm still getting a error when i'm puting the value of the _session_id even if its the "good" value as you can see on the screenshots

![dwfw](https://user-images.githubusercontent.com/74125516/98458911-a959a400-2195-11eb-8bd4-14ae0c0b70ec.png)
![szdqsd](https://user-images.githubusercontent.com/74125516/98458913-ad85c180-2195-11eb-9691-015d5f4ead4a.png)

**Comment by bitbybyte** [comment]
`Error: No valid input provided`
You didn't provide a link so it's not even verifying the cookie there.

If you login to your account from the browser first and then use that session cookie, the session will be valid.
