### ISSUE TITLE
filename definition

### ISSUE THREAD

**Issue by cm3d-legacy** [bitbybyte/fantiadl#41]
Thanks for the great tool! I have a request regarding functionality, could you please add a feature to define the filename to the post number?
ex: https://fantia.jp/posts/******/post_content_photo/[*******] or https://cc.fantia.jp/uploads/post_content_photo/file/[*******]

**Comment by bitbybyte** [comment]
Can you provide an example post (including link)?and the expected filename(s) you would want for the downloaded files?

**Comment by bitbybyte** [comment]
@cm3d-legacy Pinging for above.

**Comment by cm3d-legacy** [comment]
@bitbybyte I'm sorry I didn't notice.

For example, in this post
https://fantia.jp/posts/550160

https://fantia.jp/posts/550160/post_content_photo/3003064
https://fantia.jp/posts/550160/post_content_photo/3003065

to rename the two images to 3003064.png and 3003065.png

**Comment by e0972951006** [comment]
https://fantia.jp/posts/135591

**Comment by e0972951006** [comment]
> https://fantia.jp/posts/135591

![Uploading 5D29E720-FA97-42BA-AA74-B30F2E55CC3F.jpeg…]()
