### ISSUE TITLE
another "No Valid Input Provided" using -c or --cookie

### ISSUE THREAD

**Issue by exiagundamz** [bitbybyte/fantiadl#42]
[
![Untitled](https://user-images.githubusercontent.com/20942274/102866916-f4dcbe80-4472-11eb-9ef6-9a9380289c5f.png)
](url)
sorry for bothering you,
but i have some login problem in V1.7 
already login to fantia from chrome to get session id number,
but still got "no valid input provided" even after using -c cookies.txt / -c "insert session id here" / --cookie cookies.txt / --cookie "insert session ID here".
i already check readme and read plus following guide from previous issue that have the same problem, but it's still like this,
is this bug or there's some step i missing?
thanks for reading this

**Comment by bitbybyte** [comment]
You still aren't providing a link or an option for what to download (-f or -p). Example usage:

`fantiadl.exe --cookie a1b2c3 https://fantia.jp/posts/123`
`fantiadl.exe --cookie cookies.txt -f`
