### ISSUE TITLE
Images embedded in posts aren't downloaded in the highest resolution available

### ISSUE THREAD

**Issue by RndUser0** [bitbybyte/fantiadl#69]
Example posts (500 Yen plan):
1. https://fantia.jp/posts/679064
2. https://fantia.jp/posts/694853

Resolution differences (downloaded with fantiadl vs highest resolution):
1. Landscape: 800x565 vs 5016x3541
2. Portrait: 800x1130 vs 2508x3541

PS: I'd highly appreciate it if you would release a new binary. Thanks a lot for your work!

**Comment by bitbybyte** [comment]
I need an example on a free plan, or you can paste the response from the API:
https://api.fantia.jp/posts/694853

**Comment by RndUser0** [comment]
I didn't find an example on a free plan yet. How can I log responses from the Fantia API?

**Comment by bitbybyte** [comment]
https://fantia.jp/api/v1/posts/### while logged in, then you can attach the source as a file in a comment here.

**Comment by RndUser0** [comment]
OK, here it is: [694853.zip](https://github.com/bitbybyte/fantiadl/files/6446530/694853.zip)

**Comment by bitbybyte** [comment]
One last thing, can you verify for me what a full res URL looks like? `https://....`

**Comment by RndUser0** [comment]
Here's an example of a full res URL:
https://cc.fantia.jp/uploads/album_image/file/69076/271ad61c-0fc0-46a9-acdb-afe119dc6bcf.png?Key-Pair-Id=…&Policy=…
