### ISSUE TITLE
Where i can find this number?

### ISSUE THREAD

**Issue by rowndo** [bitbybyte/fantiadl#76]
<img width="568" alt="Screenshot 2022-01-19 164431" src="https://user-images.githubusercontent.com/98016824/150096122-00ab9ce5-fa11-4781-8d36-39090a149d78.png">

**Comment by bitbybyte** [comment]
This is a timestamp and is not strictly required when providing your session cookie. Please read the README again to verify how I retrieved the session cookie in this format.
