### ISSUE TITLE
Error because of invalid session cookie

### ISSUE THREAD

**Issue by RndUser0** [bitbybyte/fantiadl#82]
For over a week fantiadl_v1.8.exe has been displaying the error message "Error: Invalid session. Please verify your session cookie" on my PC although the session ID is correct. Of course, I copied and pasted it. I also re-logged on fantia.jp to get a new one, to no avail. Before that, it worked perfectly.

Screenshot:
![FaniaDL_v1_8-issue](https://user-images.githubusercontent.com/29837561/151276720-8ca9cefb-1626-46f4-827e-5414188d4314.png)

**Comment by bitbybyte** [comment]
Read past issues. Release will be published whenever I get around to it. #77
