### ISSUE TITLE
Invalid session despite _session_id Cookie not being expired

### ISSUE THREAD

**Issue by angramainyuu** [bitbybyte/fantiadl#84]
![image](https://user-images.githubusercontent.com/98609452/151593971-8c625cc6-3690-4091-b450-0f7fc59bafc9.png)

As the title says, I keep getting this error now for some reason and I don't understand why as the cookie isn't expired, it started a couple days ago.

I tried logging out and back in but it didn't change anything.

**Comment by bitbybyte** [comment]
v1.8 is not the newest release.
