### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by tins820** [bitbybyte/fantiadl#89]
i encountered this issue while parsing for https://fantia.jp/posts/1011234
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '...\\桃色れく\\1011234\\「🍑ももれくフレンズ🍑(月額1000円)」\x08の無料チケット'

i think it is because the backslash characters...

may i know is there any bypass solution for now?...

**Comment by bitbybyte** [comment]
Very bizzare, as `\x08` is the control character for a backspace. Sure enough, the API response has `U+0008`:

`"title": "「🍑ももれくフレンズ🍑(月額1000円)」\bの無料チケット",`

Basically we're not handling Unicode control characters at all so `\b` gets translated to `\x08` and of course the file system doesn't like that.

**Comment by bitbybyte** [comment]
It was fixed already, if you use the .exe you'll need to wait for a new release.

**Comment by tins820** [comment]
okokok thanks a lot!!!
really appreciate your effort in this project T_T
ありがとうございます！！
