### ISSUE TITLE
-n\--download-new-posts using timeline API

### ISSUE THREAD

**Issue by tins820** [bitbybyte/fantiadl#90]
i have been using this for about a week. 
really love your work.
i have a suggestion that would like to share with you and see is it ok to have a enhancement... 

i see if i am using -f or -p, it will download each fanclub one by one (i think it bases on my subscript in a reverse order) .
is it possible to have an option to download the posts in the reverse order of posting date?
(like the ordering of https://fantia.jp/mypage/posts)

**Comment by bitbybyte** [comment]
What you're really asking for is probably better implemented in a separate flag, like `--download-new-posts`. There is an API we can hit to get the same post ordering as /mypage/posts: https://fantia.jp/api/v1/me/timelines/posts?page=1&per=24
