### ISSUE TITLE
Rename downloaded folders with both id and title name

### ISSUE THREAD

**Issue by SyuueenN** [bitbybyte/fantiadl#91]
Please consider to rename downloaded folders with both id and title name. The folders named only with post id are so hard to recognise each others. People who don't know codes at all like me, recovering Japanese titles from the unicode codes ("/u1234" things) in metadata is complicated, and can't rename folders with their title at once too.

Or you can just let user to choose how to name them. Like most of Fanbox downloader extensions, has a box to fill variables like "{author}-{postid}-{title}-{filename}", to customize the output folder and how to name them.

Thanks.

(I apologise for my poor English, hopefully you can get the meanings)

**Comment by bitbybyte** [comment]
For various reasons, including the fact that post titles can change, there are no plans to change the ways paths are constructed right now.

**Comment by IIJlOXOCIIAJl** [comment]
After all this time, has anything changed? Is it possible to add a date at the beginning in the titles of downloaded posts. And that the titles of the posts match the Fantia site.
