### ISSUE TITLE
invalid session plesase verify your session cookie

### ISSUE THREAD

**Issue by ijustwantpeace** [bitbybyte/fantiadl#93]
im not good at coding and stuff i just follow the instruction of the README file but after i insert the session id it still appear invalid session please verify session cookie,i tried alot of ways to get new ones but none of it seems to work. is there a easy way get through this?

**Comment by Cranbaerry** [comment]
Still facing the same issue despite following all the instructions.
![image](https://user-images.githubusercontent.com/16867718/177075716-d672613c-4268-4c29-9e4b-7b04a3a2127c.png)
