### ISSUE TITLE
GL Error

### ISSUE THREAD

**Issue by Disposableacc65321** [bitbybyte/fantiadl#97]
I'm not sure if I did anything wrong but I:

1. Downloaded the code as a zip
2. In CMD:
`C:\Users\Joshua>cd C:\Users\User\Downloads\fantiadl-master\fantiadl-master`
3. Then
`C:\Users\User\Downloads\fantiadl-master\fantiadl-master>
fantiadl.py -c 663b4e1dedb61356e443b4078bae508a6d7757396c202efd437b48e05c8b62c1 -p -o C:\Users\User\Downloads\New folder https://fantia.jp/fanclubs/2512`

Output:

`[main 2022-10-22T12:38:50.650Z] update#setState checking for updates`
`[main 2022-10-22T12:38:50.847Z] update#setState idle`
`[17748:1022/204020.588:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is`
`[main 2022-10-22T12:40:53.152Z] Waiting for extension host with pid 8176 to exit.
`[main 2022-10-22T12:40:53.765Z] Extension host with pid 8176 exited with code: 0, signal: null.`

How do I make this work?

**Comment by bitbybyte** [comment]
Run using `python fantiadl.py`. Those look like Electron errors from a different program like VSCode being associated with .py.
